### ISSUE TITLE
Plugin breaks Yii debugbar 

### ISSUE THREAD

**Issue by troyxmccall** [diginov/craft-sentry-logger#12]
### Description

Activating this plugin breaks the Craft CMS / Yii debug bar when a user is logged in and has profiling enabled:

A simple solution would be to add 

```php
$user = Craft::$app->getUser()->getIdentity();
$debugToolbarEnabled = $user ? $user->getPreference('enableDebugToolbarForSite') : false;

if ($debugToolbarEnabled) {
  return;
}
```

to your `init()` function

### Steps to reproduce

1. login to craft admin: /admin
2. enable the debugbar for your user profile: /admin/myaccount
![Screen Shot 2024-01-10 at 1 49 32 PM](https://github.com/diginov/craft-sentry-logger/assets/129784/e568cb14-0f44-49d8-87cf-6b332a31bfee)
3. save your user settings
4. view your site, and open the network panel
5. filter for XHR requests
6. note that `/actions/debug/default/toolbar?tag=xxx` 404s 
### Additional info

- Plugin version: 1.3.4
- Craft version: 3.9.10
- PHP version: 8.1
- Configuration method: Basic

**Comment by martinleveille** [comment]
Hi @troyxmccall

I was not able to replicate the error you got. I tested with several installations having the same versions of Craft and plugin. I still get an HTTP 200 response on /actions/debug/default/toolbar?tag=[hash].

Are you able to replicate this error on other of your Craft installations?

Can you send me your composer.json to see if there are any conflicting packages?

<img width="2140" alt="sentry_logger_craft3_toolbar" src="https://github.com/diginov/craft-sentry-logger/assets/534656/ffe30db0-a30b-4a07-bc92-e2a9dae11394">

**Comment by troyxmccall** [comment]
@martinleveille, thanks for looking into this! 

It must be due to something chained if it works on a fresh install. 

We can close this for now, and I'll dig into it and see if it's another dep or even one of my (inherited) custom modules - it'll probably take me a week or two to look into this bc it's not high on my priority list at work. 

These are my composer packages, but I have a feeling it might be due to one of our private modules

```json
"require": {
        "born05/craft-assetusage": "2.3.1",
        "craftcms/cms": "3.9.6",
        "craftcms/feed-me": "4.8.0",
        "craftcms/redactor": "2.10.12",
        "diginov/craft-sentry-logger": "1.3.4",
        "ext-mbstring": "*",
        "google/cloud-bigquery": "^1.23",
        "google/cloud-core": "^1.43",
        "google/gax": "^1.9",
        "perfectwebteam/craft-mailchimp-transactional": "1.0.3",
        "verbb/super-table": "2.7.5.1",
        "vlucas/phpdotenv": "^3.4.0"
    },
 ```   
 
 thanks again!

**Comment by martinleveille** [comment]
Thank you for the feedback. I'll still take a look at an installation with your composer.json.
