### ISSUE TITLE
Setting enviroment

### ISSUE THREAD

**Issue by espensgr** [diginov/craft-sentry-logger#2]
I'm setting up this plugin to the backend with an already existing frontend in js, and that environment is not the same as the `CRAFT_ENVIRONMENT`.
Shouldn't the `SENTRY_ENVIRONMENT` be added and have presidence over the environment set in Craft? And/or be able to set this in the config.

**Comment by martinleveille** [comment]
Sure @espensgr, I will add an `environment` parameter and make a release soon.

**Comment by martinleveille** [comment]
@espensgr This should be fixed with the release 1.1.3.
