### ISSUE TITLE
Wrong pattern in preg_match for exceptPatterns-parameter?

### ISSUE THREAD

**Issue by shifted** [diginov/craft-sentry-logger#4]
https://github.com/diginov/craft-sentry-logger/blob/91f0d2a0a62b5ff04bba8d5ef1ab0dddcc75ca24/src/log/SentryTarget.php#L138

The curly braces in the pattern are treated as actual characters, so matching will never work. Or am I getting it wrong?

**Comment by martinleveille** [comment]
Hi @shifted, what is the pattern you currently want to match ?

**Comment by shifted** [comment]
Hey @martinleveille, I just need to match a handful of simple strings, eg. "cookie".

**Comment by martinleveille** [comment]
I currently have a site setup like this and it works well :

```
'exceptPatterns' => [
    'Invalid cookie auth key attempted for user',
    'Invalid session auth key attempted for user',
    'Request didn’t meet the user agent and IP requirement for maintaining a user session',
    'Tried to restore session from the the identity cookie',
]
```

What is your php and plugin version and how do you configure the plugin ? 

Here some info about curly braces syntax in PHP : [Complex (curly) syntax](https://www.php.net/manual/en/language.types.string.php#language.types.string.parsing.complex)

**Comment by shifted** [comment]
Currently on php 7.3.28 and latest (1.1.6) on sentry-logger. My config is more or less identical to yours. 
Thanks for the note about the curly braces. Makes it even stranger it doesn't work here, but the problem is clearly on my end it seems. I'll investigate further. Thanks for your help! :)

**Comment by martinleveille** [comment]
Alright @shifted let me know if you find anything. In the meantime, you can probably do a test in your local environment by modifying the `SentryTarget.php` manually in your composer vendor folder to see if this syntax `"~{$exceptPattern}~"` replaced with this one `'~'.$exceptPattern.'~'` will resolve the issue.
