### ISSUE TITLE
FR: Anonymous settings

### ISSUE THREAD

**Issue by Joobs** [diginov/craft-sentry-logger#6]
Currently there is an "anonymous" setting which stops all personal information from getting sent to Sentry.

However, for something like a membership site, some of this information can be very useful. But for GDPR reasons we don't want to send anything that can be considered personally identifiable information.

It would be useful to be able to choose what sensitive information is sent. For example a `User ID` is ok to send, but a `Username` or `Email` is not. 

Is it possible to specify which PII gets sent?

**Comment by martinleveille** [comment]
Good idea @Joobs, thanks :) I've read the documentation about the `send_default_pii` parameter and I'm thinking of disabling it in favor of manually set the user in the Sentry scope.

A good solution can be to set the `anonymous` parameter to an array of key => boolean like this. Sounds good ?

```
'enabled' => true,
'anonymous' => [
    'email' => false,
    'id' => true,
    'ip_address' => false,
    'username' => false,
],
'dsn' => App::env('SENTRY_DSN'),
'release' => App::env('SENTRY_RELEASE'),
'environment' => App::env('SENTRY_ENVIRONMENT'),
'levels' => ['error', 'warning'],
'options' => [],
'exceptCodes' => [403, 404],
'exceptPatterns' => [],
```

**Comment by Joobs** [comment]
Thanks @martinleveille I was thinking the same thing.

```
'anonymous' => [
    'email' => false,
    'id' => true,
    'ip_address' => false,
    'username'   => false,
    'Admin' => true,
    'Groups' => false,
],
```
However, I think some additional data scrubbing would be needed regarding `Cookies` and `Headers`. Looking inside the Sentry code:

```
if ($options->shouldSendDefaultPii()) {

    ...

    $requestData['cookies'] = $request->getCookieParams();
    $requestData['headers'] = $request->getHeaders();
} else {
    $requestData['headers'] = $this->sanitizeHeaders($request->getHeaders());
}
```

**Comment by martinleveille** [comment]
Hi @Joobs! This was added in the latest release using the new `userPrivacy` setting.

https://github.com/diginov/craft-sentry-logger/blob/main/README.md#userprivacy
