### ISSUE TITLE
Trace missing

### ISSUE THREAD

**Issue by JshGrn** [diginov/craft-sentry-logger#8]
### Description

I am not seeing any trace navigation, Sentry says to read the docs on how to integrate it.

### Steps to reproduce

1. Have an error in sentry and try to view the trace

### Additional info

- Plugin version: 4.1.2
- Craft version: 4.4.8
- PHP version: 8.2.2
- Configuration method: Basic

**Comment by martinleveille** [comment]
Hi @JshGrn, 

Do you know if this is a real `Exception` or just `Craft::error()` or `Craft::warning()`?

Because `Craft::error()` or `Craft::warning()` does not provide a trace.

Can you provide more information about what you see in Sentry, like a screenshot ?

**Comment by JshGrn** [comment]
Sorry I haven't replied sooner, I got some more information from Pixel & Tonic and waiting for a update to come as the warning itself doesn't provide a stack trace which is why its not showing, I think its best if this is marked as closed as I wasn't aware that this error was even happening nor it didn't provide a trace.

If required, I will re-open, but for people searching the error I am questioning is related to this: https://github.com/craftcms/cms/issues/11033
