### ISSUE TITLE
Unable to use Advanced config

### ISSUE THREAD

**Issue by pixelmachine** [diginov/craft-sentry-logger#9]
### Description

I'm trying to use the advanced config but I'm getting an error:

`PHP Fatal error:  Uncaught yii\base\ErrorException: Attempt to read property "enabled" on null in /root/craft/vendor/yiisoft/yii2/log/Dispatcher.php:187`

### Steps to reproduce

Add the app.php config:

```php
use craft\helpers\App;

return [
  '*' => [
    'components' => [
      'log' => [
        'targets' => [
          'sentry' => function() {
            if (!class_exists(SentryTarget::class)) {
              return null;
            }

            return Craft::createObject(
            [
              'class' => SentryTarget::class,
              'enabled' => true,
              'anonymous' => false,
              'dsn' => App::env('SENTRY_DSN'),
              'levels' => ['error', 'warning'],
              'exceptCodes' => [403, 404],
              'options' => [
                'max_value_length' => 2048,
              ],
            ]);
          },
        ],
      ],
    ],
  ],
];
```

### Additional info

- Plugin version: 1.3.3
- Craft version: 3.8.13
- PHP version: 8.1
- Configuration method: Advanced

**Comment by martinleveille** [comment]
Hi @pixelmachine,

Try without the `*` array because the `app.php` is not an environment-aware config file.

Also you must import the class at the top of the file with this `use diginov\sentrylogger\log\SentryTarget;`.

**Comment by martinleveille** [comment]
Hi @pixelmachine 

I think you are mixing the Craft 3 and Craft 4 advanced configuration syntax, please check this configuration example: 

https://github.com/diginov/craft-sentry-logger/tree/craft-3#craft-36-or-later

Also try without the `*` array because the `app.php` is not an environment-aware config file:

```
<?php

use craft\helpers\App;

return [

    'components' => [
        'log' => [
            'targets' => [
                '__craftSentryTarget' => function() {
                    if (!class_exists('diginov\\sentry\\log\\SentryTarget')) {
                        return null;
                    }

                    return Craft::createObject([
                        'class' => 'diginov\\sentry\\log\\SentryTarget',
                        'enabled' => true,
                        'anonymous' => false,
                        'dsn' => App::env('SENTRY_DSN'),
                        'levels' => ['error', 'warning'],
                        'exceptCodes' => [403, 404],
                        'options' => [
                            'max_value_length' => 2048,
                        ],
                    ]);
                },
            ],
        ],
    ],

];
```

**Comment by pixelmachine** [comment]
@martinleveille thanks you're totally right, I copied that Craft 4 code by mistake. I'll test it now.

**Comment by pixelmachine** [comment]
Thanks again, all good now:
<img width="683" alt="Screenshot 2023-06-12 at 1 56 07 PM" src="https://github.com/diginov/craft-sentry-logger/assets/1082223/d13bfa97-dca0-402f-9d32-3f5c9029c4b9">
